### ISSUE TITLE
TESTANDO A LINGUAGEM MARKDOWN

### ISSUE THREAD

**Issue by Joaokf** [Joaokf/Ola-Mundo#1]
estou aprendendo linguagem ~~Markdown~~ no curso em video no curso de git e github 

# Aula de linguagem __*Markdown*__
---
### Titulo

Lista numerada

1. teste
   1. teste
   2. teste
5. teste2
   
Lista demarcada

* teste
* teste
* teste
   * teste
* teste

Lista de tarefas

- [ ] Criar pagina principal
- [x] criar a pagna da loja
- [ ] finalizar a reunião com cliente
- [ ] receber pagamento

![flat,750x,075,f-pad,750x1000,f8f8f8 u5](https://user-images.githubusercontent.com/119415287/204825285-2a1178be-3d69-43eb-ade1-8e3e56083cf1.jpg)

[Acesse meu GitHub](https://Joaokf.github.io)

CRIANDO TABELA

Num | Nome | Nota 
---|---|---
1 | Joao | 9
2 | Jose | 10
3 | Laura | 5
4 | Maria | 8

Terminou a tabela

Não entendo direito para que serve o comando `document.getElementById()` da linguagem JavaScript  **OBS: Colocar crases (` `) para deixar mono espaçado e deixa o fundo cinza, para saber que é um Comando**

Olha meu progama em python

```
num = Int(input( 'Digite um valor: ')
if num %2 == 0:
    print(f' O valor {num} é PAR')
else:
   print(f' O valor {num} é IMPAR')

```

EMOJI

Olá, pequeno gafanhoto 🖖 👽 

[link da lista de emoji](https://github.com/Joaokf/emoji-list) 

**Marcar pessoas que tenham GitHub**
Como diria @CaioHalbert bora treinar

**Comment by CaioHalbert** [comment]
Aooooba, aí sim
